# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AR2Go
email: eric@squaretone.com
description: > # this means to ignore newlines until "baseurl:"
  Mobile friendly display of augmented reality markers compatible with projects like ARToolkit
baseurl: "" # the subpath of your site, e.g. /ar2go
url: "https://squaretone.github.io" # the base hostname & protocol for your site
twitter_username: AR2GoMarkers
github_project_name:  AR2Go
github_project_link:  "https://github.com/squaretone/ar2go"
google_analytics_id: "UA-239315-9"

# Customized
# @TODO: Change back to 'none'
permalink: '/:title.html'

# Build settings
markdown: kramdown

collections:
  custommarkers:
    output: true

defaults:
  - scope:
      path: ""
      type: custommarker
    values:
      layout: custommarker
      includeaframe: true
